name: Generar JSON

on:
  workflow_dispatch:
    inputs:
      nombre:
        description: "Nombre para el JSON"
        required: true
      edad:
        description: "Edad para el JSON"
        required: true
jobs:
  generate_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Crear JSON
        run: |
          echo '{ "${{ inputs.nombre }}": "${{ inputs.nombre }}", "${{ inputs.edad }}": "${{ inputs.edad }}" }' > output.json

      - name: Mostrar contenido del JSON
        run: cat output.json
