name: Generar JSON

on:
  workflow_dispatch:
    inputs:
      nombre:
        description: "Nombre del usuario"
        required: true
      edad:
        description: "Edad del usuario"
        required: true
jobs:
  generate_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Crear JSON
        run: |
          echo '{ "nombre": "${{ inputs.nombre }}", "edad": "${{ inputs.edad }}" }' > output.json

      - name: Mostrar contenido del JSON
        run: cat output.json
